[package]
name = "trudge"
version = "0.0.1"
edition = "2021"
authors = ["Robert Cofield <dev@cofield.io>"]
license = "GPL-3.0+"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
polars = "0.38.1"
